name: '🚀 publish'
on:
  push:
    branches:
      - main

jobs:
  release:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: 🟢 node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org
      - run: npm install
      - name: 🚀 publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
